import type { Metadata } from "next";
import "./globals.css";

import { css } from "@pigment-css/react";

import "@pigment-css/react/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DARK = "@media (prefers-color-scheme: dark)";

// Using object syntax
const htmlClass = css(({ theme }) => ({
  backgroundColor: theme.colorSchemes.light.colors.background,
  color: theme.colorSchemes.light.colors.foreground,
  [DARK]: {
    backgroundColor: theme.colorSchemes.dark.colors.background,
    color: theme.colorSchemes.dark.colors.foreground,
  },
}));

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={htmlClass}>
      <body>
        {children}
      </body>
    </html>
  );
}
